### ISSUE TITLE
Feedme.wav

### ISSUE THREAD

**Issue by MateusLikesCake** [miatribe/Pavlov#1]
So, everytime the feed countdown reaches 0, I got an error message about a missing "feedme.wav" file. I have no ideia how to fix this haha

(PS: I'm a totally noob with this platform and addons stuff, so I'm very grateful for this one haha)

**Comment by miatribe** [comment]
This was my fault. I left the file out of the zip. I have updated the download to include it. 

So re-download the zip and extract all the files out (it now includes the feedme.wav).
https://github.com/miatribe/Pavlov/releases/download/0.3/Pavlov.zip

Thanks for finding this!
