### ISSUE TITLE
Get memory addresses of the game?

### ISSUE THREAD

**Issue by misa3l** [miatribe/Pavlov#2]
Hello, I have a question from a few days ago and I decide to ask. I'm trying to get the same memory locations that you used to get the information on the mascot and the homunculus.

https://github.com/miatribe/Pavlov/blob/master/Pavlov/MemRead.cs#L41

but I have not been able to find these addresses, I would like to know if you are kind enough to explain to me the way in which you obtained the addresses. I'm using OLLYDBG, what software do you use? and how did you get the addresses? I would like to explain a little, thank you very much for your help.

**Comment by miatribe** [comment]
I used Cheat engine to get the values, but you should be able to see them in OLLYDBG.

I don't include the actual memory address in the app as they can change (although they rarely do) and use a method called signature scanning to get the addresses at runtime.

Below are same saved values I used - the hex values should be the memory locations.
![image](https://user-images.githubusercontent.com/7443428/52242460-c1a3dd00-28a4-11e9-92e4-287c1388b8c9.png)

**Comment by miatribe** [comment]
For the string types yes... But a lot of them are not strings (lat ,lon are numbers for example)

**Comment by misa3l** [comment]
ok ok, I'm trying at this moment and I can see the name of the homunculus and other things ... what I do not understand is how you got to this position:

0F B6 84 0F ?? ?? ?? ?? 30 81
8B 43 07 A3 ?? ?? ?? ?? 85 FF

I already understood the signature scanning, what I do not give is with that specific position that I am indicating to you ..

**Comment by miatribe** [comment]
The homon name should be at 00EA10E8 (this is a memory location) 

0F B6 84 0F ?? ?? ?? ?? 30 81
8B 43 07 A3 ?? ?? ?? ?? 85 FF

these are masks... like you are looking at all the byytes in memory and looking for that pattern, the ?? ?? ?? ?? are unknown

**Comment by misa3l** [comment]
I already understood, I managed to locate the position successfully.

What would the pattern be like to get that name? I think this is my last question.

![memoria homunculo](https://user-images.githubusercontent.com/7856540/52245507-43e9cc80-28b8-11e9-8660-8a5c6fd0e8d2.png)

**Comment by misa3l** [comment]
here would be the name of the homunculus, I'm trying to get the pattern but I can not get it xD

![2](https://user-images.githubusercontent.com/7856540/52247782-af846780-28c1-11e9-9ef0-13ec2b69d92c.png)
![1](https://user-images.githubusercontent.com/7856540/52247784-b0b59480-28c1-11e9-841c-dc9329fdf3b4.png)

**Comment by miatribe** [comment]
You are going to have to look online to find a guide. I have not worked on this stuff for I believe over a year now, so i'm very rusty (I had to download and install Ragnarok today to get the values for you). It looks like you are on the right track though! Goodluck.

**Comment by misa3l** [comment]
do you play ragnarok iro renewal? I'm new xD, if you cheer up we'll see you in the game.

**Comment by miatribe** [comment]
Nope I don't RO anymore.

**Comment by misa3l** [comment]
sell me a ghosting :v jeje, ty for help me.

**Comment by misa3l** [comment]
any email to contact you?

**Comment by miatribe** [comment]
No sorry. I'm not going to be able to assist you with anything, I'm not in a situation where I'm actively developing this type of application anymore (I'll work on this one in case of an issue). And since it's been quite some time since I done something like this, it would require me to relearn what I believe you are going to ask me.
